# استفاده از تصویر پایه Ubuntu
FROM python:3.12-alpine
# به‌روز رسانی سیستم و نصب پکیج‌های مورد نیاز
RUN apk add --no-cache redis gcc musl-dev libffi-dev

# تعیین دایرکتوری کار
WORKDIR /app

# کپی کردن فایل requirements.txt به دایرکتوری کار
COPY requirements.txt .

# نصب کتابخانه‌های Python مورد نیاز
EXPOSE 6379


RUN pip install --break-system-packages --no-cache-dir -r requirements.txt

# کپی کردن کدهای برنامه به دایرکتوری کار
COPY . .
# راه‌اندازی Redis در پس‌زمینه
RUN redis-server --daemonize yes

RUN redis-server
# اجرای Celery
CMD ["celery", "-A", "khabaramKon", "worker", "--loglevel=info"]

